package com.mxdeploy.api.domain;

import java.io.Serializable;

 /**
  * Url Value Object.
  * This class is value object representing database table TB_URL
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class Url implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private String id;
    private String id_project;
    private String name;
    private String url;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public Url () {

    }

    public Url (String idIn) {

          this.id = idIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public String getId() {
          return this.id;
    }
    public void setId(String idIn) {
          this.id = idIn;
    }

    public String getIdProject() {
          return this.id_project;
    }
    public void setIdProject(String id_projectIn) {
          this.id_project = id_projectIn;
    }

    public String getName() {
          return this.name;
    }
    public void setName(String nameIn) {
          this.name = nameIn;
    }

    public String getUrl() {
          return this.url;
    }
    public void setUrl(String urlIn) {
          this.url = urlIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(String idIn,
          String id_projectIn,
          String nameIn,
          String urlIn) {
          this.id = idIn;
          this.id_project = id_projectIn;
          this.name = nameIn;
          this.url = urlIn;
    }


    /** 
     * hasEqualMapping-method will compare two Url instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(Url valueObject) {

          if (this.id == null) {
                    if (valueObject.getId() != null)
                           return(false);
          } else if (!this.id.equals(valueObject.getId())) {
                    return(false);
          }
          if (this.id_project == null) {
                    if (valueObject.getIdProject() != null)
                           return(false);
          } else if (!this.id_project.equals(valueObject.getIdProject())) {
                    return(false);
          }
          if (this.name == null) {
                    if (valueObject.getName() != null)
                           return(false);
          } else if (!this.name.equals(valueObject.getName())) {
                    return(false);
          }
          if (this.url == null) {
                    if (valueObject.getUrl() != null)
                           return(false);
          } else if (!this.url.equals(valueObject.getUrl())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass Url, mapping to table TB_URL\n");
        out.append("Persistent attributes: \n"); 
        out.append("id = " + this.id + "\n"); 
        out.append("id_project = " + this.id_project + "\n"); 
        out.append("name = " + this.name + "\n"); 
        out.append("url = " + this.url + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        Url cloned = new Url();

        if (this.id != null)
             cloned.setId(new String(this.id)); 
        if (this.id_project != null)
             cloned.setIdProject(new String(this.id_project)); 
        if (this.name != null)
             cloned.setName(new String(this.name)); 
        if (this.url != null)
             cloned.setUrl(new String(this.url)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}

